// @generated by protoc-gen-es v2.3.0 with parameter "target=ts"
// @generated from file sf/substreams/v1/test/test.proto (package sf.substreams.v1.test, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sf/substreams/v1/test/test.proto.
 */
export const file_sf_substreams_v1_test_test: GenFile = /*@__PURE__*/
  fileDesc("CiBzZi9zdWJzdHJlYW1zL3YxL3Rlc3QvdGVzdC5wcm90bxIVc2Yuc3Vic3RyZWFtcy52MS50ZXN0IiMKBUJsb2NrEgoKAmlkGAEgASgJEg4KBm51bWJlchgCIAEoBCI1CglNYXBSZXN1bHQSFAoMYmxvY2tfbnVtYmVyGAEgASgEEhIKCmJsb2NrX2hhc2gYAiABKAkiGQoHQm9vbGVhbhIOCgZyZXN1bHQYASABKAgiFwoFQXJyYXkSDgoGcmVzdWx0GAEgAygJIhsKCkludDY0VmFsdWUSDQoFdmFsdWUYASABKANCUFpOZ2l0aHViLmNvbS9zdHJlYW1pbmdmYXN0L3N1YnN0cmVhbXMvcGIvc2Yvc3Vic3RyZWFtcy92MS90ZXN0LztwYnN1YnN0cmVhbXN0ZXN0YgZwcm90bzM");

/**
 * @generated from message sf.substreams.v1.test.Block
 */
export type Block = Message<"sf.substreams.v1.test.Block"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: uint64 number = 2;
   */
  number: bigint;
};

/**
 * Describes the message sf.substreams.v1.test.Block.
 * Use `create(BlockSchema)` to create a new message.
 */
export const BlockSchema: GenMessage<Block> = /*@__PURE__*/
  messageDesc(file_sf_substreams_v1_test_test, 0);

/**
 * @generated from message sf.substreams.v1.test.MapResult
 */
export type MapResult = Message<"sf.substreams.v1.test.MapResult"> & {
  /**
   * @generated from field: uint64 block_number = 1;
   */
  blockNumber: bigint;

  /**
   * @generated from field: string block_hash = 2;
   */
  blockHash: string;
};

/**
 * Describes the message sf.substreams.v1.test.MapResult.
 * Use `create(MapResultSchema)` to create a new message.
 */
export const MapResultSchema: GenMessage<MapResult> = /*@__PURE__*/
  messageDesc(file_sf_substreams_v1_test_test, 1);

/**
 * @generated from message sf.substreams.v1.test.Boolean
 */
export type Boolean = Message<"sf.substreams.v1.test.Boolean"> & {
  /**
   * @generated from field: bool result = 1;
   */
  result: boolean;
};

/**
 * Describes the message sf.substreams.v1.test.Boolean.
 * Use `create(BooleanSchema)` to create a new message.
 */
export const BooleanSchema: GenMessage<Boolean> = /*@__PURE__*/
  messageDesc(file_sf_substreams_v1_test_test, 2);

/**
 * @generated from message sf.substreams.v1.test.Array
 */
export type Array = Message<"sf.substreams.v1.test.Array"> & {
  /**
   * @generated from field: repeated string result = 1;
   */
  result: string[];
};

/**
 * Describes the message sf.substreams.v1.test.Array.
 * Use `create(ArraySchema)` to create a new message.
 */
export const ArraySchema: GenMessage<Array> = /*@__PURE__*/
  messageDesc(file_sf_substreams_v1_test_test, 3);

/**
 * @generated from message sf.substreams.v1.test.Int64Value
 */
export type Int64Value = Message<"sf.substreams.v1.test.Int64Value"> & {
  /**
   * @generated from field: int64 value = 1;
   */
  value: bigint;
};

/**
 * Describes the message sf.substreams.v1.test.Int64Value.
 * Use `create(Int64ValueSchema)` to create a new message.
 */
export const Int64ValueSchema: GenMessage<Int64Value> = /*@__PURE__*/
  messageDesc(file_sf_substreams_v1_test_test, 4);

